version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/home/Users/gabrielrcp/Documents/docker-workspace/compose/elk/temp
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

# docker network create elastic
# docker pull docker.elastic.co/elasticsearch/elasticsearch:7.15.2
# docker run --name es01-test --net elastic -p 127.0.0.1:9200:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.15.2


# docker pull docker.elastic.co/kibana/kibana:7.15.2
# docker run --name kib01-test --net elastic -p 127.0.0.1:5601:5601 -e "ELASTICSEARCH_HOSTS=http://es01-test:9200" docker.elastic.co/kibana/kibana:7.15.2

# version: '3'
# services:
#   es01:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
#     container_name: es01
#     environment:
#       - node.name=es01
#       - cluster.name=es-docker-cluster
#       - discovery.type=single-node
#     volumes:
#       - data01:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#       - 9300:9300
#     networks:
#       - elastic

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.15.2
#     environment:
#       - ELASTICSEARCH_HOSTS=http://es01-test:9200    
#     volumes:
#       - ./kibana.yml:/usr/share/kibana/config/kibana.yml  
#     ports:
#       - 5601:5601
#     networks:
#       - elastic
#     depends_on:
#       - es01

#   networks:
#     elastic:
#       driver: bridge